### ISSUE TITLE
incorrect formular in hotelling t-squared confidence interval

### ISSUE THREAD

**Issue by ccshao** [nevernervous78/nirpyresearch#2] opened 2022-11-09 15:07 UTC
Thanks for the tutorial on outlier detection (https://nirpyresearch.com/outliers-detection-pls-regression-nir-spectroscopy-python/), very helpful for a beginner like me. 

However, I found there might be a mistake about the confidence interval of hotelling t-squared.
```
Tsq_conf =  f.ppf(q=conf, dfn=ncomp, \
            dfd=X2.shape[0])*ncomp*(X2.shape[0]-1)/(X2.shape[0]-ncomp)
```
With X2.shape[0] as number of samples, and ncomp as latent variable.

The correct one appears to be
```
Tsq_conf =  f.ppf(q=conf, dfn=ncomp, \
            dfd=(X2.shape[0]- ncomp))*ncomp*(X2.shape[0]-1)/(X2.shape[0]-ncomp)
```

Ref
https://www.itl.nist.gov/div898/handbook/pmc/section5/pmc543.htm
https://en.wikipedia.org/wiki/Hotelling%27s_T-squared_distribution

**Comment by nevernervous78** [comment] 2022-11-13 09:26
Thanks for that! You're quite right and I'll be fixing this in the post asap.

**Comment by kikesama10** [comment] 2023-01-10 22:58
Hello, I follow your blog since I am also working with spectral data. I would like to consult you in the same tutorial (https://nirpyresearch.com/outliers-detection-pls-regression-nir-spectroscopy-python/), in the Q-residuals section:

`while 1-np.sum(Q&gt;i)/np.sum(Q&gt;0) &gt; conf:
    i -= 1`

Why is (;) used? I have an error executing that operator.

**Comment by nevernervous78** [comment] 2023-01-11 00:43
Thanks for letting me know. There was some problem in the rendering of the Python code into Wordpress and the symbol ">" was rendered as "&gt;". It should be fixed now, including the chance to the Tsq formula. 

Thanks very much for alerting me about the problem :)

**Closed as completed** 2023-01-11 00:43 UTC
